name: Node.js CI

on:
  push:
    branches:
      - main # You can specify your main branch name here
      - dev
      - test
  pull_request:
    branches:
      - main
      - dev 
      - test


  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    #firest merged with main
    - name: Checkout
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/checkout@v2


    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage dev --region ap-south-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

